es:
  id: ${ES_ID}
  password: ${ES_PASSWORD}
  endpoint: ${ES_ENDPOINT}

general:
  user-agent: ${USER_AGENT}

springdoc:
  version: 1.0.0
  swagger-ui:
    # path: /swagger-ui.html
    disable-swagger-default-url: false
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    password: ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USERNAME}
  jpa:
#    profiles:
#      active: local
#      group:
#        local: logging-type-condole, logging-level-local
#        dev: logging-type-file, logging-level-dev
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
