es:
  id: ${ES_ID}
  password: ${ES_PASSWORD}
  endpoint: ${ES_ENDPOINT}

general:
  user-agent: ${USER_AGENT}

springdoc:
  version: 1.0.0
  swagger-ui:
    # path: /swagger-ui.html
    disable-swagger-default-url: false
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs